include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - avoid_print
    - use_super_parameters
    - prefer_single_quotes
